[package]
name = "cthulhu-angel-sm"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre = "0.6.5"
cthulhu-common = { path = "../common" }
regex = "1.11.1"
swexpect = { git = "https://github.com/rewbycraft/swexpect.git" }
tracing = "0.1"
