[package]
name = "cthulhu-config"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre = "0.6.5"
serde = { version = "1.0.219", features = ["derive"] }
tokio = { version = "1.45.1", features = ["full"] }
toml = "0.8.23"
tracing = "0.1.41"
